name: Plans Daily Monitor on Win/Mac

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
    inputs:
      test_url:
        description: 'Test URL'
        required: false
        type: string

jobs:
  monitor:
    strategy:
      matrix:
        include:
          - os: windows-latest
            browser: chromium
          - os: macos-latest
            browser: webkit
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Run plans monitor
        run: npx playwright test plans/monitor.spec.js --project=${{ matrix.browser }}
        env:
          TEST_URL: ${{ inputs.test_url }}
          USER_AGENT_SUFFIX: "${{ secrets.USER_AGENT_SUFFIX }}"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: plans-monitor-results-${{ matrix.browser }}-${{ github.run_number }}
          path: |
            playwright-report/
            screenshots/
          retention-days: 30

      - name: Slack notification on success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: good
          SLACK_ICON: https://github.com/actions.png?size=48
          SLACK_USERNAME: Plans US Monitor on ${{ matrix.browser }}
          SLACK_MSG_AUTHOR: ""
          MSG_MINIMAL: true
          SLACK_TITLE: ✅ Plans US Monitor 🇺🇸 - SUCCESS
          SLACK_MESSAGE: |
            Test URL: https://www.adobe.com/creativecloud/plans.html
            View details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SLACK_FOOTER: ""
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack notification on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_ICON: https://github.com/actions.png?size=48
          SLACK_USERNAME: Plans US Monitor on ${{ matrix.browser }}
          SLACK_MSG_AUTHOR: ""
          MSG_MINIMAL: true
          SLACK_MESSAGE: |
            Test URL: https://www.adobe.com/creativecloud/plans.html
            View details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          SLACK_TITLE: ❌ Plans US Monitor 🇺🇸 - FAILURE
          SLACK_FOOTER: ""
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

