name: Plans Daily Monitor on Android

on:
  workflow_dispatch:
    inputs:
      test_url:
        description: 'Test URL'
        required: false
        type: string

jobs:
  monitor:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            browser: chrome
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10
          
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
          
      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          profile: Pixel 8 
          script: |
            adb devices
            npx appium driver list
            mkdir -p ${{ github.workspace }}/log
            adb logcat > ${{ github.workspace }}/log/adblogcat.txt
            npx wdio wdio-android.conf.js
        env:
          TEST_URL: ${{ inputs.test_url }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: plans-monitor-results-${{ matrix.browser }}-${{ github.run_number }}
          path: |
            screenshots/
            log/
          retention-days: 30




