name: Plans Daily Monitor on Win/Mac

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
    inputs:
      test_url:
        description: 'Test URL'
        required: false
        type: string

jobs:
  monitor:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            browser: chromium
          # - os: macos-latest
          #   browser: webkit
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Run plans monitor
        run: npx playwright test plans/monitor.spec.js --project=${{ matrix.browser }}
        env:
          TEST_URL: ${{ inputs.test_url }}
          USER_AGENT_SUFFIX: "${{ secrets.USER_AGENT_SUFFIX }}"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: plans-monitor-results-${{ matrix.browser }}-${{ github.run_number }}
          path: |
            playwright-report/
            screenshots/
          retention-days: 30

      - name: Slack notification on success
        if: success()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "channel": "loot-loaders-tests",
              "username": "Plans US Monitor",
              "icon_url": "https://github.com/actions.png?size=48",
              "attachments": [
                {
                  "color": "good",
                  "title": "✅ Plans US Monitor 🇺🇸 - SUCCESS",
                  "text": "OS: ${{ matrix.os }}\nBrowser: ${{ matrix.browser }}\nTest URL: https://www.adobe.com/creativecloud/plans.html\nView details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Slack notification on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "channel": "loot-loaders-tests",
              "username": "Plans US Monitor",
              "icon_url": "https://github.com/actions.png?size=48",
              "attachments": [
                {
                  "color": "danger",
                  "title": "❌ Plans US Monitor 🇺🇸 - FAILURE",
                  "text": "OS: ${{ matrix.os }}\nBrowser: ${{ matrix.browser }}\nTest URL: https://www.adobe.com/creativecloud/plans.html\nView details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

